| Field Name    | Description                                      |
| ------------- | ------------------------------------------------ |
| `inter_dom`     | Types of students (international or domestic)   |
| `japanese_cate` | Japanese language proficiency                    |
| `english_cate`  | English language proficiency                     |
| `academic`      | Current academic level (undergraduate or graduate) |
| `age`           | Current age of student                           |
| `stay`          | Current length of stay in years                  |
| `todep`         | Total score of depression (PHQ-9 test)           |
| `tosc`          | Total score of social connectedness (SCS test)   |
| `toas`          | Total score of acculturative stress (ASISS test) |

In [ ]:

SELECT * 
FROM students;

    inter_dom region  gender  ... alone_bi  others_bi  internet_bi
0       Inter    SEA    Male  ...       No         No           No
1       Inter    SEA    Male  ...       No         No           No
2       Inter    SEA    Male  ...       No         No           No
3       Inter     EA  Female  ...       No         No           No
4       Inter     EA  Female  ...       No         No           No
..        ...    ...     ...  ...      ...        ...          ...
281                           ...
282                           ...
283                           ...
284                           ...
285                           ...

[286 rows x 50 columns]

In [ ]:
-- Find the number of international students and their average scores by length of stay, in descending order of length of stay

SELECT stay, 
       COUNT(*) AS count_int,
       ROUND(AVG(todep), 2) AS average_phq, 
       ROUND(AVG(tosc), 2) AS average_scs, 
       ROUND(AVG(toas), 2) AS average_as
FROM students
WHERE inter_dom = 'Inter'
GROUP BY stay
ORDER BY stay DESC;

   stay  count_int  average_phq  average_scs  average_as
0    10          1        13.00        32.00       50.00
1     8          1        10.00        44.00       65.00
2     7          1         4.00        48.00       45.00
3     6          3         6.00        38.00       58.67
4     5          1         0.00        34.00       91.00
5     4         14         8.57        33.93       87.71
6     3         46         9.09        37.13       78.00
7     2         39         8.28        37.08       77.67
8     1         95         7.48        38.11       72.80

In [7]:
SELECT stay, ROUND(AVG(todep), 2) AS average_phq
FROM students
WHERE inter_dom = 'Inter'
GROUP BY stay
ORDER BY stay;

   stay  average_phq
0     1         7.48
1     2         8.28
2     3         9.09
3     4         8.57
4     5         0.00
5     6         6.00
6     7         4.00
7     8        10.00
8    10        13.00

In [8]:
import plotly.express as px

fig = px.bar(stay_depression, x='stay', y='average_phq',
             labels={'stay': 'Length of Stay (years)', 'average_phq': 'Average Depression Score (PHQ-9)'},
             title='Average Depression Score by Length of Stay for International Students',
             text='average_phq')
fig.update_traces(texttemplate='%{text:.2f}', textposition='outside')
fig.update_layout(yaxis_range=[0, max(stay_depression['average_phq'])+2])
fig.show()

In [9]:
SELECT tosc, todep
FROM students
WHERE inter_dom = 'Inter';

     tosc  todep
0      34      0
1      48      2
2      41      2
3      37      3
4      37      3
..    ...    ...
196    37      6
197    16      7
198    25     16
199    38      8
200    47      2

[201 rows x 2 columns]

In [10]:
fig1 = px.scatter(scs_depression, x='tosc', y='todep',
                 labels={'tosc': 'Social Connectedness Score (SCS)', 'todep': 'Depression Score (PHQ-9)'},
                 title='Social Connectedness vs. Depression for International Students',
                 trendline='ols')
fig1.show()

In [11]:
SELECT toas, todep
FROM students
WHERE inter_dom = 'Inter';

     toas  todep
0      91      0
1      39      2
2      51      2
3      75      3
4      82      3
..    ...    ...
196    82      6
197   145      7
198   110     16
199    68      8
200    57      2

[201 rows x 2 columns]

In [12]:
import plotly.express as px
fig2 = px.scatter(as_depression, x='toas', y='todep',
                 labels={'toas': 'Acculturative Stress Score (ASISS)', 'todep': 'Depression Score (PHQ-9)'},
                 title='Acculturative Stress vs. Depression for International Students',
                 trendline='ols')
fig2.show()

In [13]:
SELECT stay, todep
FROM students
WHERE inter_dom = 'Inter';

     stay  todep
0       5      0
1       1      2
2       6      2
3       1      3
4       1      3
..    ...    ...
196     3      6
197     1      7
198     3     16
199     1      8
200     2      2

[201 rows x 2 columns]

In [14]:
fig3 = px.scatter(stay_depression, x='stay', y='todep',
                 labels={'stay': 'Length of Stay (years)', 'todep': 'Depression Score (PHQ-9)'},
                 title='Length of Stay vs. Depression for International Students',
                 trendline='ols')
fig3.show()